### PR TITLE
BUG: notebook fixes

### PR DESCRIPTION
**Pull request by deniederhut**
Removes fstrings; removes mid-integer unders; adds lifetimes==0.6.0.0 to reqfile to fix importerror; replaces is/notna with is/notnull.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks.

What's the plan for where the materials will be run? The tutorial instructions link to https://github.com/deniederhut/Pandas-Tutorial-SciPyConf-2018 so maybe this PR should be there?

**Comment by deniederhut** [comment]
The PR targets the nb-update branch, which you created here.

**Comment by TomAugspurger** [comment]
> Removes fstrings; removes mid-integer unders;

Which commits are these in?

FWIW, I'm perfectly happy requiring Python 3.6. I've found that requiring exact versions helps cut down on install issue the day of the tutorial.

> adds lifetimes==0.6.0.0

Got that in https://github.com/deniederhut/Pandas-Tutorial-SciPyConf-2018/pull/4

> replaces is/notna with is/notnull

We want the `na` versions. Pandas hasn't deprecated the `null` versions yet, but we're documenting `na` as the preferred way.

**Comment by deniederhut** [comment]
> Which commits are these in?

BUG: removes 3.6-only syntax

> I'm perfectly happy requiring Python 3.6

I'm not sure it's a good idea. An early frustration that students have is with teaching materials that only work with a very specific setup. I don't think we should assume that people attending the tutorials will have enough familiarity with Python to know what bits of syntax were introduced in 3.5 versus 3.6 versus 3.7.

> we're documenting na as the preferred way

I'm not sure that `isna` works under 0.20.

**Comment by TomAugspurger** [comment]
> An early frustration that students have is with teaching materials that
only work with a very specific setup. I don't think we should assume that
people attending the tutorials will have enough familiarity with Python to
know what bits of syntax were introduced in 3.5 versus 3.6 versus 3.7.

Agreed with that sentiment, we should avoid newer syntax. But I do think
the instructions should recommend a specific version to avoid install
issues.

> I'm not sure that isna works under 0.20.

It was added in 0.21.0.

**Pull request closed without merging**
